#!/bin/bash

set -e

deployment_name=cf-diego
target_env=superlaser
host_name=bosh
vm_name=
user_name=vcap
is_dusts=false

function usage() {
  >&2 cat <<EOF

SYNOPSIS:
  Bosh SSH Helper
    Performs the following steps
    1) bosh target
    2) bosh download manifest to a temporary file
    3) bosh ssh (including setting gateway information)

USAGE:
  $0 [OPTIONAL ARGUMENTS]

OPTIONAL ARGUMENTS:
  -d <deployment-name>   Name of the BOSH Deployment (default: cf-diego)
  -t <target-name>       Name of the BOSH Target env.  Must be in deployments-runtime and match a "target" in bosh target (default: superlaser)
  -h <host-prefix>       Prefix of bosh director hostname (default: bosh)
  -v <vm-name>           Name of the VM to connect to (e.g. database_z1/0)
  -u <user-name>         Name of the user in BOSH director (default: vcap)
  -D                     DUSTs target (overrides -d, -t, -u with DUSTs specific info)
EOF
  exit 1
}

while getopts "d:t:h:v:u:D" opt; do
  case $opt in
    d)
      deployment_name=$OPTARG
      ;;
    t)
      target_env=$OPTARG
      ;;
    h)
      host_name=$OPTARG
      ;;
    v)
      vm_name=$OPTARG
      ;;
    u)
      user_name=$OPTARG
      ;;
    D)
      is_dusts=true
      ;;
    *)
      echo "Unknown arguments"
      usage
      ;;
  esac
done

temp_file=$(mktemp -d -t boshssh)/${target_env}-${deployment_name}-${RANDOM}.yml
if [ ${is_dusts} == 'true' ]; then

  bosh target ${target_env}

  bosh download manifest ${deployment_name} ${temp_file}

  bosh -d ${temp_file} ssh --gateway_user ubuntu --gateway_host ${host_name}.${target_env}.diego-ci.cf-app.com --gateway_identity_file ~/workspace/deployments-runtime/diego-ci/keypair/id_rsa_bosh ${vm_name} --strict_host_key_checking no

else

  bosh target ${target_env}

  bosh download manifest ${deployment_name} ${temp_file}

  bosh -d ${temp_file} ssh --gateway_user ${user_name} --gateway_host ${host_name}.${target_env}.cf-app.com --gateway_identity_file ~/workspace/deployments-runtime/${target_env}/keypair/id_rsa_bosh ${vm_name} --strict_host_key_checking no

fi

rm ${temp_file}
